micronaut:
  application:
    name: shrink-ln
  security:
    enabled: true
    intercept-url-map:
      -
        pattern: "/swagger*"
        http-method: GET
        access:
          - isAnonymous()
#datasources:
#  default:
#    url: ${JDBC_URL:`jdbc:oracle:thin:@localhost:1521/xe`}
#    driverClassName: ${JDBC_DRIVER:oracle.jdbc.driver.OracleDriver}
#    username: ${JDBC_USER:system}
#    password: ${JDBC_PASSWORD:welcome}
#    schema-generate: CREATE_DROP
#    dialect: ORACLE

datasources:
  default:
    url: jdbc:h2:mem:devDb;MVCC=TRUE;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2

jpa.default.properties.hibernate.hbm2ddl.auto: update